apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: de-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    path: /guestbook/guestbook-ui-deployment.yaml
    targetRevision: HEAD
  destination: 
    name: hub
    namespace: default